### ISSUE TITLE
SHA384 Hash to Convert JSON Web Token

### ISSUE THREAD

**Issue by ashraful1980** [mazen160/jwt-pwn#3]
Dear Sir,
I would like to draw your kind attention i have questions that it is possible to generate JSON Web Token from SHA384 Hash. If it is possible please advice how it is possible.
Also please generate JSON Web Token from my SHA384 hash: e648d207eb6a457cc3b415e5e6db38759de529051d808b5d34c679c43020a233e6b5161de2e85070127009d61e4c24c8 

Thanks & Regards,
Md. Ashraful Alam

**Comment by mazen160** [comment]
Hi @ashraful1980 

Thank you for your message. It's not possible to generate a JWT from a string. It's only possible to generate a JWT from a JSON object.

If the hash is a JSON object, then a JWT can be generated.

Please check: https://pyjwt.readthedocs.io/en/latest/

Best,
Mazin
