### ISSUE TITLE
fix python3 file read issues

### ISSUE THREAD

**Issue by siovador** [mazen160/jwt-pwn#4]
need to update codec as default utf8 wont cut it for rockyou.txt.

open(file, "r",encoding="ISO-8859-1")

**Comment by mazen160** [comment]
Hi @heaphopopotamus 

The issue appears to be happening on Python 3 when reading non UTF-8 characters. I pushed a fix to this issue at https://github.com/mazen160/jwt-pwn/commit/380a049512f74087d4a8871c0e20ae9151e8c970.

Presetting non UTF-8 encoding for file read may introduce file read issues with wordlists.

The commit should fix it now. Please reopen the issue ticket if it's still there. 

Thanks!
Mazin
